### What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, basic linear algebra, basic statistical operations, random simulation and much more.

In [12]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np

### Numpy Arrays vs Python Lists
| Aspect            | Numpy Arrays                             | Python Lists                              |
|-------------------|------------------------------------------|-------------------------------------------|
| Data Types        | Homogeneous (same data type)            | Heterogeneous (can contain any data type)|
| Performance       | More efficient for numerical operations | Less efficient for numerical operations  |
| Functionality     | Specialized functions for numerical ops| General-purpose methods for common tasks |
| Memory Overhead   | Less memory overhead                    | More memory overhead                      |
| Usage             | Numerical and scientific computing      | General-purpose programming               |


An "array" is a central data structure of the NumPy library.<br>
The elements are all of the same type, referred to as the array "dtype".<br>
The "rank" of the array is the number of dimensions.<br>
The "shape" of the array is a tuple of integers giving the size of the array along each dimension.<br>
"vector" is an array with a single dimension <br>
"matrix" refers to an array with two dimensions <br>
"tensor" refers to an array with three or more dimensions <br>
"dimensions" are also called "axes". <br>

In [14]:
#  initialize NumPy arrays
a = np.array([1, 2, 3, 4, 5, 6])
a = np.array([[1, 2, 3], [4, 5, 6]])
a = np.zeros(2)  # [0., 0.]
a = np.ones(2)  # [1., 1.]
a = np.random.rand(2, 2)  # uniform in [0, 1]
a = np.arange(10)  # 0 .. n-1
a = np.linspace(0, 10, num=5)
# 5 numbers between 0 .. 10, evenly spaced array([0. , 2.5, 5. , 7.5, 10.])
a = np.empty(2)  # uninitialized
# 2x3 array with all elements 7: array([[7, 7, 7], [7, 7, 7]])
a = np.full((2, 3), 7)
a[0]  # zero-based indexing

array([7, 7, 7])

In [15]:
# Adding, removing, and sorting elements
a = np.array([1, 2, 3])
a = np.append(a, [4, 5, 6])
a = np.insert(a, 1, 10)
a = np.delete(a, [1])
a = np.sort(a)
b = np.array([1, 2, 3])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [16]:
a = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],

              [[0, 1, 2, 3],
               [4, 5, 6, 7]],

              [[0, 1, 2, 3],
               [4, 5, 6, 7]]])

print(a.ndim)  # number of dimensions
print(a.size)  # number of elements
print(a.shape)  # shape of the array

3
24
(3, 2, 4)


In [17]:
# reshape
a = np.arange(6)
print(a)
a = a.reshape(3, 2)
print(a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [18]:
# convert a 1D array into a 2D array using np.newaxis, np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
a2.shape

(6,)


(1, 6)

In [19]:
# Indexing and slicing

# same ways as Python lists.
a = np.array([0, 1, 2])
print(a[0])
print(a[0:2])
print(a[-1])
print(a[-2:])

0
[0 1]
2
[1 2]


In [20]:
# conditional indexing
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 7])
print(a[a % 2 == 0])
print(a[(a > 2) & (a < 11)])

[1 2 3 4 5 6]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]


In [21]:
# Basic array operations
# additiion, subtraction, multiplication, division, square root, exponentiation operators
data = np.array([1, 2])
ones = np.ones(2)
print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)
print(np.sqrt(data))
print(np.exp(data))

[2. 3.]
[0. 1.]
[1. 2.]
[1. 2.]
[1.         1.41421356]
[2.71828183 7.3890561 ]


In [22]:
data = np.array([1, 2])
print(data.sum())
print(data.min())
print(data.max())

3
1
2


In [23]:
# get unique items and counts
a = np.array([1, 2, 2, 3, 3, 3])
unique_values = np.unique(a)
unique_values, unique_values.size

(array([1, 2, 3]), 3)

In [24]:
# ransposing a matrix
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.T)
print(data.transpose())
print(data.reshape(2, 3))

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
[[1 2 3]
 [4 5 6]]


In [25]:
# reversing an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)
reversed_arr = np.flip(arr)
print(reversed_arr)
# reversing a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
reversed_arr = np.flip(arr)
print(reversed_arr)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
