In [1]:
from pandas import read_csv
import numpy as np

In [2]:
dataset = read_csv('social_media_dataset.csv')

In [3]:
dataset

age  income  gender   platform  interests        location demographics  \
0     56   19774    male  Instagram     Sports  United Kingdom        Urban   
1     46   10564  female   Facebook     Travel  United Kingdom        Urban   
2     32   13258    male  Instagram     Sports       Australia    Sub_Urban   
3     60   12500    male  Instagram     Travel  United Kingdom        Urban   
4     25   14566    male  Instagram  Lifestlye       Australia        Urban   
..   ...     ...     ...        ...        ...             ...          ...   
995   22   18536  female  Instagram  Lifestlye  United Kingdom        Rural   
996   40   12711    male    YouTube     Travel  United Kingdom        Rural   
997   27   17595    male    YouTube     Travel  United Kingdom        Rural   
998   61   16273  female    YouTube     Sports       Australia    Sub_Urban   
999   19   16284  female    YouTube     Travel       Australia        Rural   

            profession  indebt  isHomeOwner  Owns_Car  time_spent  
0    Software Engineer    True        False     False           3  
1              Student    True         True      True           2  
2     Marketer Manager   False        False     False           8  
3              Student   False         True     False           5  
4    Software Engineer   False         True      True           1  
..                 ...     ...          ...       ...         ...  
995   Marketer Manager   False         True     False           8  
996  Software Engineer    True        False     False           6  
997            Student    True        False      True           5  
998   Marketer Manager    True         True     False           4  
999            Student   False         True     False           8  

[1000 rows x 12 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   age           1000 non-null   int64 
 1   income        1000 non-null   int64 
 2   gender        1000 non-null   object
 3   platform      1000 non-null   object
 4   interests     1000 non-null   object
 5   location      1000 non-null   object
 6   demographics  1000 non-null   object
 7   profession    1000 non-null   object
 8   indebt        1000 non-null   bool  
 9   isHomeOwner   1000 non-null   bool  
 10  Owns_Car      1000 non-null   bool  
 11  time_spent    1000 non-null   int64 
dtypes: bool(3), int64(3), object(6)
memory usage: 73.4+ KB


In [5]:
dataset.describe()  # Descriptive statistics

age        income   time_spent
count  1000.000000   1000.000000  1000.000000
mean     40.986000  15014.823000     5.029000
std      13.497852   2958.628221     2.537834
min      18.000000  10012.000000     1.000000
25%      29.000000  12402.250000     3.000000
50%      42.000000  14904.500000     5.000000
75%      52.000000  17674.250000     7.000000
max      64.000000  19980.000000     9.000000

In [6]:
# Extracting the independent variables (features)
X = dataset.iloc[:, :-1].values
X

array([[56, 19774, 'male', ..., True, False, False],
       [46, 10564, 'female', ..., True, True, True],
       [32, 13258, 'male', ..., False, False, False],
       ...,
       [27, 17595, 'male', ..., True, False, True],
       [61, 16273, 'female', ..., True, True, False],
       [19, 16284, 'female', ..., False, True, False]], dtype=object)

In [7]:
# Extracting the dependent variable (label) => 'time spent on social media platform'
y = dataset.iloc[:, -1].values
y

array([3, 2, 8, 5, 1, 3, 8, 4, 7, 2, 7, 5, 5, 6, 9, 6, 8, 7, 9, 4, 2, 7,
       6, 1, 9, 9, 2, 3, 5, 5, 1, 8, 8, 4, 7, 3, 6, 9, 1, 5, 4, 8, 1, 9,
       6, 4, 9, 5, 5, 5, 1, 1, 8, 8, 6, 4, 2, 2, 9, 5, 4, 1, 7, 3, 6, 5,
       5, 5, 1, 1, 3, 4, 5, 2, 8, 2, 9, 2, 9, 7, 8, 2, 7, 6, 4, 7, 4, 2,
       7, 8, 2, 5, 1, 7, 8, 6, 5, 6, 2, 1, 7, 7, 2, 2, 1, 8, 8, 1, 8, 9,
       4, 1, 1, 3, 5, 5, 9, 2, 2, 6, 9, 1, 9, 9, 9, 5, 9, 4, 2, 6, 4, 6,
       3, 6, 2, 2, 9, 7, 3, 1, 8, 6, 7, 9, 5, 1, 7, 5, 3, 9, 1, 1, 1, 3,
       6, 3, 8, 2, 9, 3, 5, 8, 2, 6, 5, 9, 5, 2, 5, 4, 7, 6, 2, 5, 7, 7,
       5, 9, 4, 3, 4, 5, 6, 3, 2, 4, 5, 4, 3, 8, 4, 2, 2, 1, 4, 9, 7, 7,
       7, 8, 1, 8, 4, 4, 4, 6, 7, 6, 1, 8, 7, 6, 6, 5, 6, 9, 9, 8, 9, 8,
       8, 1, 5, 4, 2, 8, 3, 4, 7, 9, 2, 3, 4, 1, 7, 2, 5, 1, 3, 2, 1, 7,
       5, 1, 6, 5, 3, 7, 9, 9, 9, 2, 3, 7, 5, 2, 3, 6, 7, 9, 1, 7, 8, 3,
       4, 6, 7, 4, 8, 5, 1, 4, 3, 9, 8, 1, 6, 9, 7, 4, 1, 2, 5, 5, 8, 6,
       8, 2, 3, 6, 3, 6, 6, 2, 7, 2, 6, 1, 3, 2, 7,

In [8]:
# scaling the age and income features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[:, 0:2] = scaler.fit_transform(X[:, 0:2])

In [9]:
X

array([[1.1128817500082018, 1.609380435596781, 'male', ..., True, False,
        False],
       [0.37165239739850314, -1.5051063363485266, 'female', ..., True,
        True, True],
       [-0.666068696255075, -0.5940935932843944, 'male', ..., False,
        False, False],
       ...,
       [-1.0366833725599243, 0.87252194742427, 'male', ..., True, False,
        True],
       [1.483496426313051, 0.42546966593548646, 'female', ..., True,
        True, False],
       [-1.6296668546476831, 0.4291894655545308, 'female', ..., False,
        True, False]], dtype=object)

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [11]:
imputer.fit(X[:, :])
X = imputer.transform(X[:, :])

In [12]:
X

array([[1.1128817500082018, 1.609380435596781, 'male', ..., True, False,
        False],
       [0.37165239739850314, -1.5051063363485266, 'female', ..., True,
        True, True],
       [-0.666068696255075, -0.5940935932843944, 'male', ..., False,
        False, False],
       ...,
       [-1.0366833725599243, 0.87252194742427, 'male', ..., True, False,
        True],
       [1.483496426313051, 0.42546966593548646, 'female', ..., True,
        True, False],
       [-1.6296668546476831, 0.4291894655545308, 'female', ..., False,
        True, False]], dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
transformer = ColumnTransformer(
    transformers=[("categorical_encoder", OneHotEncoder(), [2, 3, 4, 5, 6, 7])], remainder='passthrough')

In [15]:
X = np.array(transformer.fit_transform(X))

In [16]:
X

array([[0.0, 1.0, 0.0, ..., True, False, False],
       [1.0, 0.0, 1.0, ..., True, True, True],
       [0.0, 1.0, 0.0, ..., False, False, False],
       ...,
       [0.0, 1.0, 0.0, ..., True, False, True],
       [1.0, 0.0, 0.0, ..., True, True, False],
       [1.0, 0.0, 0.0, ..., False, True, False]], dtype=object)

In [17]:
# Encoding True/False values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in [19, 20, 21]:
    X[:, i] = le.fit_transform(X[:, i])

In [18]:
X

array([[0.0, 1.0, 0.0, ..., 1, 0, 0],
       [1.0, 0.0, 1.0, ..., 1, 1, 1],
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       ...,
       [0.0, 1.0, 0.0, ..., 1, 0, 1],
       [1.0, 0.0, 0.0, ..., 1, 1, 0],
       [1.0, 0.0, 0.0, ..., 0, 1, 0]], dtype=object)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.1, random_state=1)

In [20]:
print("X_train shape: ", X_train.shape)
print("X_test shape: ", X_test.shape)
print("y_train shape: ", y_train.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (900, 22)
X_test shape:  (100, 22)
y_train shape:  (900,)
y_test shape:  (100,)


In [21]:
X_train

array([[0.0, 1.0, 0.0, ..., 0, 0, 1],
       [1.0, 0.0, 0.0, ..., 0, 1, 0],
       [0.0, 1.0, 1.0, ..., 1, 0, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 0, 1],
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       [0.0, 1.0, 0.0, ..., 1, 1, 0]], dtype=object)

In [22]:
X_test

array([[1.0, 0.0, 1.0, ..., 1, 1, 1],
       [0.0, 1.0, 0.0, ..., 0, 0, 1],
       [0.0, 1.0, 1.0, ..., 1, 1, 0],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 0, 1],
       [1.0, 0.0, 0.0, ..., 1, 1, 1],
       [0.0, 1.0, 0.0, ..., 0, 1, 0]], dtype=object)

In [23]:
y_train

array([2, 6, 8, 8, 5, 6, 4, 3, 5, 7, 5, 9, 5, 5, 2, 7, 5, 6, 9, 7, 4, 8,
       5, 4, 4, 1, 6, 9, 6, 4, 6, 9, 3, 8, 5, 8, 3, 8, 4, 5, 2, 2, 7, 9,
       1, 7, 8, 8, 8, 5, 3, 5, 7, 7, 2, 2, 1, 6, 4, 7, 3, 6, 5, 6, 2, 2,
       6, 1, 1, 9, 4, 2, 9, 6, 5, 8, 5, 5, 4, 8, 9, 1, 5, 3, 1, 7, 1, 4,
       2, 3, 4, 8, 1, 6, 4, 4, 8, 2, 1, 6, 4, 4, 9, 5, 4, 3, 4, 7, 2, 9,
       6, 9, 8, 7, 4, 4, 6, 9, 7, 4, 7, 9, 4, 4, 8, 8, 1, 4, 4, 6, 1, 9,
       2, 8, 6, 4, 1, 7, 5, 5, 8, 7, 8, 7, 3, 4, 7, 7, 2, 3, 3, 5, 8, 4,
       6, 8, 3, 2, 3, 6, 1, 8, 4, 8, 8, 2, 9, 8, 4, 8, 2, 1, 8, 1, 3, 5,
       2, 3, 3, 2, 3, 7, 8, 9, 3, 6, 5, 4, 2, 7, 3, 4, 8, 7, 5, 5, 3, 1,
       3, 7, 9, 5, 4, 5, 8, 8, 6, 2, 6, 8, 4, 2, 8, 1, 9, 7, 6, 9, 9, 6,
       7, 2, 6, 1, 3, 3, 6, 5, 7, 6, 9, 3, 7, 7, 2, 6, 5, 6, 8, 9, 5, 5,
       5, 5, 2, 7, 4, 2, 8, 1, 1, 5, 2, 6, 9, 6, 3, 3, 6, 9, 9, 6, 3, 6,
       1, 4, 8, 2, 1, 1, 5, 2, 1, 9, 1, 2, 8, 9, 8, 4, 7, 7, 3, 1, 9, 9,
       4, 7, 5, 5, 6, 8, 7, 8, 9, 2, 1, 2, 2, 6, 2,

In [24]:
y_test

array([8, 1, 8, 9, 5, 5, 8, 3, 5, 5, 2, 7, 6, 9, 8, 6, 1, 8, 6, 8, 1, 4,
       8, 5, 6, 6, 8, 6, 5, 2, 5, 6, 9, 8, 3, 8, 9, 7, 5, 3, 1, 6, 2, 7,
       8, 5, 2, 8, 7, 8, 4, 7, 4, 3, 3, 1, 5, 4, 1, 4, 7, 3, 2, 9, 4, 6,
       3, 3, 6, 7, 3, 3, 7, 6, 2, 5, 2, 1, 1, 4, 2, 8, 7, 6, 3, 9, 1, 4,
       7, 5, 4, 8, 4, 4, 7, 1, 9, 7, 7, 6], dtype=int64)

In [25]:
# Saving the preprocessed data
import csv
with open("preprocessed.csv", 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)

    # Concatenate X with y
    concatenated_data = np.concatenate((X, y.reshape(-1, 1)), axis=1)

    # write the concatenated data
    for row in concatenated_data:
        writer.writerow(row)